=== Asszi/THORXS_XMLGyak/XMLTaskTHORXS/XMLSchemaTHORXS.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema targetNamespace="thorxs" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="full_addressType">
    <xs:sequence>
      <xs:element type="xs:string" name="country"/>
      <xs:element type="xs:string" name="zip"/>
      <xs:element type="xs:string" name="city"/>
      <xs:element type="xs:string" name="address"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="bookType" mixed="true">
    <xs:sequence>
      <xs:element name="title" />
      <xs:element name="isbn" />
      <xs:element name="publish_date" />
      <xs:element type="authorsType" name="authors" />
      <xs:element type="ratingsType" name="ratings" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>

  <xs:complexType name="booksType">
    <xs:sequence>
      <xs:element type="bookType" name="book" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="libraryType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="full_addressType" name="full_address"/>
      <xs:element type="booksType" name="books"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>

  <xs:complexType name="librariesType">
    <xs:sequence>
      <xs:element type="libraryType" name="library"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="authorType" mixed="true">
    <xs:sequence>
      <xs:element type="nameType" name="name"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>

  <xs:complexType name="authorsType">
    <xs:sequence>
      <xs:element type="authorType" name="author" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ratingType">
    <xs:sequence>
      <xs:element name="name" />
      <xs:element name="comment" />
      <xs:element name="value" />
      <xs:element name="date" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>

  <xs:complexType name="ratingsType">
    <xs:sequence>
      <xs:element type="ratingType" name="rating" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="nameType">
    <xs:sequence>
      <xs:element name="first_name" />
      <xs:element name="last_name" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="database">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="librariesType" name="libraries"/>
        <xs:element type="booksType" name="books"/>
        <xs:element type="ratingsType" name="ratings"/>
        <xs:element type="authorsType" name="authors"/>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="libraryId">
      <xs:selector xpath="./libraries/library"/>
      <xs:field xpath="@id" />
    </xs:key>
    <xs:key name="bookId">
      <xs:selector xpath="./books/book"/>
      <xs:field xpath="@id" />
    </xs:key>
    <xs:key name="authorID">
      <xs:selector xpath="./authors/author"/>
      <xs:field xpath="@id" />
    </xs:key>
    <xs:key name="ratingID">
      <xs:selector xpath="./ratings/rating"/>
      <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="bookRef" refer="bookId">
      <xs:selector xpath="./libraries/library/books/book"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
    <xs:keyref name="authorRef" refer="authorId">
      <xs:selector xpath="./books/book/authors/author"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
    <xs:keyref name="ratingRef" refer="ratingID">
      <xs:selector xpath="./books/book/ratings/rating"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
  </xs:element>
</xs:schema>

=== Asszi/THORXS_XMLGyak/XMLTaskTHORXS/domparsethorxs/src/main/resources/XMLTHORXS.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="thorxs"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="thorxs XMLSchemaTHORXS.xsd">
    <libraries>
        <library id="1">
            <name>Test Library</name>
            <full_address>
                <country>Hungary</country>
                <zip>3980</zip>
                <city>Satoraljaujhely</city>
                <address>Petofi ut. 4.</address>
            </full_address>
            <books>
                <book idref="1" />
            </books>
        </library>
    </libraries>

    <books>
        <book id="1">
            <title>The Book</title>
            <isbn>1254386759283</isbn>
            <publish_date>2020-05-01</publish_date>
            <authors>
                <author idref="1" />
            </authors>
            <ratings>
                <rating idref="1" />
            </ratings>
        </book>
        <book id="2">
            <title>Another Book</title>
            <isbn>1254336759583</isbn>
            <publish_date>2021-05-01</publish_date>
            <authors>
                <author idref="2" />
                <author idref="3" />
            </authors>
            <ratings>
                <rating idref="2" />
                <rating idref="3" />
            </ratings>
        </book>
    </books>

    <ratings>
        <rating id="1">
            <name>randomcommenter</name>
            <comment>Very good! Best book ever!</comment>
            <value>5.0</value>
            <date>2021-12-12</date>
        </rating>
        <rating id="2">
            <name>user123</name>
            <comment>It was okay</comment>
            <value>4.1</value>
            <date>2021-11-03</date>
        </rating>
        <rating id="3">
            <name>someoneee</name>
            <comment>Interesting</comment>
            <value>4.5</value>
            <date>2021-05-12</date>
        </rating>
    </ratings>

    <authors>
        <author id="1">
            <name>
                <first_name>Elek</first_name>
                <last_name>Teszt</last_name>
            </name>
        </author>
        <author id="2">
            <name>
                <first_name>Bela</first_name>
                <last_name>Kiss</last_name>
            </name>
        </author>
        <author id="3">
            <name>
                <first_name>Alan</first_name>
                <last_name>Poe</last_name>
            </name>
        </author>
    </authors>
</database>
